package runtimeauth

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Shared test vector, generated by the runtime's OWN libraries (werkzeug
// generate_password_hash and flask_jwt_extended create_access_token) and
// pinned here verbatim.
//
// The Go side of the bootloader reimplements two formats the Python side owns.
// That is the same hazard as the ctypes mirror in shared/plugin_runtime_args.py:
// the two can drift apart silently, and the symptom is every login failing on a
// device nobody can log into to diagnose. The identical values are asserted
// from Python in tests/pytest/restapi/test_bootloader_auth_vector.py, so a
// werkzeug or PyJWT upgrade that changes either format breaks a test on the
// side that changed rather than a device in the field.
const (
	vectorPepper   = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	vectorPassword = "correct horse battery staple"
	vectorHash     = "pbkdf2:sha256:600000$WCXqtZujfdFXqzAB$" +
		"4be2d44037a7d62f2483d1a189bd2dacb66871b323871f185a73a8e2d3230611"

	vectorSecret = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
	// Minted for user id 7. Its exp is a fixed timestamp, so tests assert the
	// signature and the decoded claims directly rather than routing it through
	// VerifyToken -- otherwise the result would depend on how long ago the
	// vector happened to be generated.
	vectorToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9." +
		"eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4ODQ2NTIwMCwianRpIjoiNWYwNjVlOTctM2M2NC00" +
		"ZGU0LWFlYmYtMDMyZjdjNDM5M2M3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjciLCJuYmYi" +
		"OjE3ODg0NjUyMDAsImNzcmYiOiJjMThiMDFiMy05NmVjLTQwZDQtYjJmZS1jNjVhYTNiZjUx" +
		"NTciLCJleHAiOjE3ODg0NjYxMDB9." +
		"xM9AVtdXVFd5mU6gWm842aHwVQpYybL4A3EMyEWSLjc"
)

// --- passwords -----------------------------------------------------------

func TestVerifiesAHashWerkzeugProduced(t *testing.T) {
	ok, err := VerifyPassword(vectorHash, vectorPassword, vectorPepper)
	if err != nil {
		t.Fatalf("verifying the shared vector: %v", err)
	}
	if !ok {
		t.Fatal("the shared vector must verify; Go and Python have drifted apart")
	}
}

func TestTheWrongPasswordIsRejected(t *testing.T) {
	ok, err := VerifyPassword(vectorHash, "not the password", vectorPepper)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ok {
		t.Fatal("a wrong password must not verify")
	}
}

func TestThePepperIsRequired(t *testing.T) {
	// User.set_password appends the pepper before hashing. Dropping it, or
	// prepending instead of appending, fails every login while looking
	// perfectly reasonable in review -- hence an explicit test.
	ok, _ := VerifyPassword(vectorHash, vectorPassword, "")
	if ok {
		t.Fatal("verification must fail without the pepper")
	}
	ok, _ = VerifyPassword(vectorHash, vectorPepper+vectorPassword, "")
	if ok {
		t.Fatal("the pepper is appended, not prepended")
	}
}

func TestAnUnknownHashSchemeIsReportedNotTreatedAsAMismatch(t *testing.T) {
	// An operator needs to see "this runtime hashes differently", not
	// "wrong password", or they will chase the wrong problem.
	_, err := VerifyPassword("scrypt:32768:8:1$salt$abcd", "x", "")
	if !errors.Is(err, ErrUnsupportedHash) {
		t.Fatalf("want ErrUnsupportedHash, got %v", err)
	}
}

func TestAnAbsurdIterationCountIsRefused(t *testing.T) {
	// A hostile or corrupt hash must not be able to spend unbounded CPU in the
	// component that exists to recover the device.
	_, err := VerifyPassword("pbkdf2:sha256:999999999$salt$abcd", "x", "")
	if !errors.Is(err, ErrUnsupportedHash) {
		t.Fatalf("want ErrUnsupportedHash for a huge iteration count, got %v", err)
	}
}

// --- tokens --------------------------------------------------------------

func TestOurHMACAgreesWithPyJWTOnTheWireFormat(t *testing.T) {
	// The cross-language check, kept because it is what proves the base64url
	// variant and the "header.payload" framing agree with flask_jwt_extended.
	// It signs with the RUNTIME's secret directly, which is what PyJWT did --
	// this is a statement about the encoding, not about which tokens we accept.
	parts := strings.Split(vectorToken, ".")
	if len(parts) != 3 {
		t.Fatalf("vector token is malformed: %d segments", len(parts))
	}
	mac := hmac.New(sha256.New, []byte(vectorSecret))
	mac.Write([]byte(parts[0] + "." + parts[1]))
	got := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	if got != parts[2] {
		t.Fatalf("encoding disagrees with PyJWT:\n want %s\n  got %s", parts[2], got)
	}
}

func TestARuntimeTokenIsNotAcceptedByTheBootloader(t *testing.T) {
	// The two services share a credential database, NOT a session. They
	// previously shared JWT_SECRET_KEY directly, which made a 2-hour
	// bootloader token a valid runtime token -- eight times the runtime's own
	// TTL, and revoked by neither side's logout. The bootloader now signs with
	// a key derived from that secret, so a real runtime token fails here on
	// the signature.
	if _, err := VerifyToken(vectorSecret, vectorToken); err == nil {
		t.Fatal("a runtime-issued token was accepted by the bootloader")
	}
}

func TestABootloaderTokenIsNotValidForTheRuntime(t *testing.T) {
	// The other direction, checked the way the runtime would: flask_jwt_extended
	// verifies HS256 with JWT_SECRET_KEY itself.
	token, err := IssueToken(vectorSecret, "7", time.Hour)
	if err != nil {
		t.Fatalf("issuing: %v", err)
	}
	parts := strings.Split(token, ".")
	mac := hmac.New(sha256.New, []byte(vectorSecret))
	mac.Write([]byte(parts[0] + "." + parts[1]))
	asRuntimeWouldSign := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	if asRuntimeWouldSign == parts[2] {
		t.Fatal("a bootloader token carries a signature the runtime would accept")
	}
}

func TestABootloaderTokenNamesThisServiceAsItsAudience(t *testing.T) {
	// Belt and braces on top of the derived key: legible in a decoded token,
	// and it would catch a future change that reunified the signing keys.
	token, err := IssueToken(vectorSecret, "7", time.Hour)
	if err != nil {
		t.Fatalf("issuing: %v", err)
	}
	claims, err := VerifyToken(vectorSecret, token)
	if err != nil {
		t.Fatalf("verifying our own token: %v", err)
	}
	if claims.Audience != Audience {
		t.Errorf("aud = %q, want %q", claims.Audience, Audience)
	}
}

func TestATokenWithoutOurAudienceIsRefused(t *testing.T) {
	// Correctly signed but minted for something else, e.g. a bootloader from
	// before the audience existed. Refused, so it cannot be replayed here.
	noAudience := signedToken(t, vectorSecret, Claims{
		Subject: "7", Type: TokenType,
		IssuedAt: time.Now().Unix(), NotBefore: time.Now().Unix(),
		Expires: time.Now().Add(time.Hour).Unix(), JTI: "test",
	})
	if _, err := VerifyToken(vectorSecret, noAudience); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("want ErrInvalidToken for a token with no audience, got %v", err)
	}
}

func TestARealFlaskTokenDecodesToTheExpectedIdentity(t *testing.T) {
	// sub is str(user.id), per the runtime's user_identity_lookup. A username
	// here would yield a token the runtime accepts structurally and then fails
	// to resolve to a user.
	parts := strings.Split(vectorToken, ".")
	raw, err := decodeSegment(parts[1])
	if err != nil {
		t.Fatalf("decoding vector payload: %v", err)
	}
	var claims Claims
	if err := json.Unmarshal(raw, &claims); err != nil {
		t.Fatalf("unmarshalling vector claims: %v", err)
	}
	if claims.Subject != "7" {
		t.Fatalf("want subject 7, got %q", claims.Subject)
	}
	if claims.Type != TokenType {
		t.Fatalf("want type %q, got %q", TokenType, claims.Type)
	}
}

// signedToken hand-builds a correctly signed token with the given claims, so
// a test can exercise a claim state IssueToken will not produce (it clamps a
// non-positive TTL to the default, on purpose).
func signedToken(t *testing.T, secret string, claims Claims) string {
	t.Helper()
	header, err := json.Marshal(jwtHeader{Alg: "HS256", Typ: "JWT"})
	if err != nil {
		t.Fatalf("encoding header: %v", err)
	}
	payload, err := json.Marshal(claims)
	if err != nil {
		t.Fatalf("encoding claims: %v", err)
	}
	input := encodeSegment(header) + "." + encodeSegment(payload)
	return input + "." + sign(secret, input)
}

func TestAnExpiredTokenIsReportedAsExpiredNotInvalid(t *testing.T) {
	// The distinction is what lets the API tell a caller that logging in again
	// will help, instead of leaving them to guess.
	past := time.Now().Add(-2 * time.Hour).Unix()
	expired := signedToken(t, vectorSecret, Claims{
		Subject: "7", Type: TokenType,
		IssuedAt: past, NotBefore: past, Expires: past + 60, JTI: "test",
		Audience: Audience,
	})
	if _, err := VerifyToken(vectorSecret, expired); !errors.Is(err, ErrTokenExpired) {
		t.Fatalf("want ErrTokenExpired, got %v", err)
	}
}

func TestATokenFromTheFutureIsRejected(t *testing.T) {
	future := time.Now().Add(2 * time.Hour).Unix()
	notYet := signedToken(t, vectorSecret, Claims{
		Subject: "7", Type: TokenType,
		IssuedAt: future, NotBefore: future, Expires: future + 3600, JTI: "test", Audience: Audience,
	})
	if _, err := VerifyToken(vectorSecret, notYet); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("want ErrInvalidToken for a not-yet-valid token, got %v", err)
	}
}

func TestATamperedTokenIsRejected(t *testing.T) {
	tampered := vectorToken[:len(vectorToken)-4] + "AAAA"
	if _, err := VerifyToken(vectorSecret, tampered); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("want ErrInvalidToken for a tampered signature, got %v", err)
	}
}

func TestTheWrongSecretIsRejected(t *testing.T) {
	if _, err := VerifyToken(strings.Repeat("c", 64), vectorToken); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("want ErrInvalidToken for the wrong secret, got %v", err)
	}
}

func TestAlgNoneIsNotHonoured(t *testing.T) {
	// The classic JWT vulnerability. The algorithm is never read from the
	// header here, so a token asking for "none" simply fails the HMAC check.
	// eyJhbGciOiJub25lIn0 = {"alg":"none"}
	forged := "eyJhbGciOiJub25lIn0.eyJzdWIiOiIxIiwidHlwZSI6ImFjY2VzcyJ9."
	if _, err := VerifyToken(vectorSecret, forged); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("alg=none must be refused, got %v", err)
	}
}

func TestIssuedTokensRoundTrip(t *testing.T) {
	token, err := IssueToken(vectorSecret, "42", time.Hour)
	if err != nil {
		t.Fatalf("issuing: %v", err)
	}
	claims, err := VerifyToken(vectorSecret, token)
	if err != nil {
		t.Fatalf("verifying our own token: %v", err)
	}
	if claims.Subject != "42" {
		t.Fatalf("want subject 42, got %q", claims.Subject)
	}
	if claims.Type != TokenType {
		t.Fatalf("want type %q, got %q", TokenType, claims.Type)
	}
}

func TestAnIssuedTokenCarriesTheClaimsTheRuntimeChecks(t *testing.T) {
	// The runtime must accept a token the bootloader minted during recovery, so
	// the claim set has to match what flask_jwt_extended requires.
	token, err := IssueToken(vectorSecret, "7", time.Hour)
	if err != nil {
		t.Fatalf("issuing: %v", err)
	}
	claims, err := VerifyToken(vectorSecret, token)
	if err != nil {
		t.Fatalf("verifying: %v", err)
	}
	if claims.JTI == "" || claims.IssuedAt == 0 || claims.Expires == 0 || claims.NotBefore == 0 {
		t.Fatalf("missing a required claim: %+v", claims)
	}
}

func TestARefreshTokenIsNotAcceptedAsAnAccessToken(t *testing.T) {
	// Hand-build a token whose type is wrong but whose signature is valid.
	token, err := IssueToken(vectorSecret, "1", time.Hour)
	if err != nil {
		t.Fatalf("issuing: %v", err)
	}
	// Flip the type claim and re-sign so only the type is at fault.
	parts := strings.Split(token, ".")
	payload, err := decodeSegment(parts[1])
	if err != nil {
		t.Fatalf("decoding payload: %v", err)
	}
	swapped := strings.Replace(string(payload), `"type":"access"`, `"type":"refresh"`, 1)
	if swapped == string(payload) {
		t.Fatal("test could not find the type claim to swap")
	}
	rebuilt := parts[0] + "." + encodeSegment([]byte(swapped))
	forged := rebuilt + "." + sign(vectorSecret, rebuilt)

	if _, err := VerifyToken(vectorSecret, forged); !errors.Is(err, ErrInvalidToken) {
		t.Fatalf("a refresh token must not authenticate, got %v", err)
	}
}

// --- secrets -------------------------------------------------------------

func writeEnv(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), ".env")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing env: %v", err)
	}
	return path
}

func TestLoadsTheRuntimeSecrets(t *testing.T) {
	path := writeEnv(t, "FLASK_ENV=development\n"+
		"SQLALCHEMY_DATABASE_URI=sqlite:////var/lib/openplc-runtime/restapi.db\n"+
		"JWT_SECRET_KEY="+vectorSecret+"\nPEPPER="+vectorPepper+"\n")
	secrets, err := LoadSecrets(path)
	if err != nil {
		t.Fatalf("loading: %v", err)
	}
	if secrets.JWTSecret != vectorSecret || secrets.Pepper != vectorPepper {
		t.Fatal("secrets did not round-trip")
	}
}

func TestAMissingSecretIsFatalRatherThanEmpty(t *testing.T) {
	// An empty signing key would accept tokens signed with an empty key --
	// strictly worse than refusing to start.
	path := writeEnv(t, "PEPPER="+vectorPepper+"\n")
	if _, err := LoadSecrets(path); err == nil {
		t.Fatal("a .env with no JWT_SECRET_KEY must be refused")
	}
}

// --- user store ----------------------------------------------------------

// seedDB builds a database shaped like the runtime's and returns its path.
func seedDB(t *testing.T, withTable bool, rows ...[4]string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "restapi.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("creating db: %v", err)
	}
	defer db.Close()

	if withTable {
		if _, err := db.Exec(`CREATE TABLE users (
			id INTEGER PRIMARY KEY,
			username TEXT NOT NULL UNIQUE,
			password_hash TEXT NOT NULL,
			role TEXT NOT NULL DEFAULT 'admin')`); err != nil {
			t.Fatalf("creating table: %v", err)
		}
		for _, row := range rows {
			if _, err := db.Exec(
				"INSERT INTO users (id, username, password_hash, role) VALUES (?, ?, ?, ?)",
				row[0], row[1], row[2], row[3]); err != nil {
				t.Fatalf("seeding user: %v", err)
			}
		}
	} else {
		// A runtime that never started leaves a file with no schema.
		if _, err := db.Exec("CREATE TABLE placeholder (x INTEGER)"); err != nil {
			t.Fatalf("creating placeholder: %v", err)
		}
	}
	return path
}

func TestAuthenticatesAgainstTheRuntimeDatabase(t *testing.T) {
	path := seedDB(t, true, [4]string{"7", "operator", vectorHash, "admin"})
	store, err := OpenUserStore(path)
	if err != nil {
		t.Fatalf("opening store: %v", err)
	}
	defer store.Close()

	user, err := store.Authenticate(context.Background(), "operator", vectorPassword, vectorPepper)
	if err != nil {
		t.Fatalf("authenticating: %v", err)
	}
	if user.ID != "7" {
		t.Fatalf("want id 7, got %q", user.ID)
	}
	if user.Role != "admin" {
		t.Fatalf("want role admin, got %q", user.Role)
	}
}

func TestAnUnknownUserAndABadPasswordAreIndistinguishable(t *testing.T) {
	// Answering differently for the two enumerates valid usernames.
	path := seedDB(t, true, [4]string{"1", "operator", vectorHash, "admin"})
	store, err := OpenUserStore(path)
	if err != nil {
		t.Fatalf("opening store: %v", err)
	}
	defer store.Close()
	ctx := context.Background()

	_, unknownErr := store.Authenticate(ctx, "nobody", vectorPassword, vectorPepper)
	_, badPassErr := store.Authenticate(ctx, "operator", "wrong", vectorPepper)

	if !errors.Is(unknownErr, ErrNoSuchUser) || !errors.Is(badPassErr, ErrNoSuchUser) {
		t.Fatalf("both must report ErrNoSuchUser, got %v and %v", unknownErr, badPassErr)
	}
}

func TestCountUsersDrivesTheBootstrapRefusal(t *testing.T) {
	// With no accounts the bootloader accepts nothing: first-user bootstrap
	// belongs to the runtime alone.
	empty := seedDB(t, true)
	store, err := OpenUserStore(empty)
	if err != nil {
		t.Fatalf("opening store: %v", err)
	}
	defer store.Close()

	count, err := store.CountUsers(context.Background())
	if err != nil {
		t.Fatalf("counting: %v", err)
	}
	if count != 0 {
		t.Fatalf("want 0 users, got %d", count)
	}
}

func TestADatabaseWithNoSchemaCountsAsNoUsers(t *testing.T) {
	// A runtime that has never started leaves the file present but empty.
	// That is the no-users case, not a broken database.
	path := seedDB(t, false)
	store, err := OpenUserStore(path)
	if err != nil {
		t.Fatalf("opening store: %v", err)
	}
	defer store.Close()

	count, err := store.CountUsers(context.Background())
	if err != nil {
		t.Fatalf("an unschema'd database must not be an error: %v", err)
	}
	if count != 0 {
		t.Fatalf("want 0 users, got %d", count)
	}
}

func TestAMissingRoleColumnValueDefaultsToAdmin(t *testing.T) {
	// Databases predating RBAC are migrated in place; until then the column
	// can be NULL, and the pre-RBAC runtime treated every account as admin.
	path := filepath.Join(t.TempDir(), "restapi.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("creating db: %v", err)
	}
	if _, err := db.Exec(`CREATE TABLE users (
		id INTEGER PRIMARY KEY, username TEXT, password_hash TEXT, role TEXT)`); err != nil {
		t.Fatalf("creating table: %v", err)
	}
	if _, err := db.Exec(
		"INSERT INTO users (id, username, password_hash, role) VALUES (3, 'old', ?, NULL)",
		vectorHash); err != nil {
		t.Fatalf("seeding: %v", err)
	}
	db.Close()

	store, err := OpenUserStore(path)
	if err != nil {
		t.Fatalf("opening store: %v", err)
	}
	defer store.Close()

	user, err := store.FindUser(context.Background(), "old")
	if err != nil {
		t.Fatalf("finding user: %v", err)
	}
	if user.Role != "admin" {
		t.Fatalf("a NULL role must resolve to admin, got %q", user.Role)
	}
}

// --- absent database -----------------------------------------------------

func TestANilStoreReportsRatherThanPanics(t *testing.T) {
	// On a device whose runtime has never started there is no restapi.db, and
	// the bootloader still has to come up so an operator can find out why. A
	// typed nil assigned to an interface is not nil at the call site, so
	// without these guards the first request would panic the process into a
	// Docker restart loop -- on precisely the device that most needs a way in.
	var store *UserStore
	ctx := context.Background()

	if _, err := store.CountUsers(ctx); !errors.Is(err, ErrNoDatabase) {
		t.Fatalf("CountUsers: want ErrNoDatabase, got %v", err)
	}
	if _, err := store.FindUser(ctx, "op"); !errors.Is(err, ErrNoDatabase) {
		t.Fatalf("FindUser: want ErrNoDatabase, got %v", err)
	}
	if _, err := store.Authenticate(ctx, "op", "pw", vectorPepper); !errors.Is(err, ErrNoDatabase) {
		t.Fatalf("Authenticate: want ErrNoDatabase, got %v", err)
	}
	if err := store.Close(); err != nil {
		t.Fatalf("Close on a nil store must be a no-op, got %v", err)
	}
}
