/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-1-ga49a51a

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"
#include <string.h>

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

#define OD_RPDO_COMM_DEFAULT(cob_id) \
    { .highestSub_indexSupported = 0x05, .COB_IDUsedByRPDO = (cob_id), \
      .transmissionType = 0xFE, .eventTimer = 0x0000 }
#define OD_RPDO_MAPPING_DEFAULT \
    { .numberOfMappedApplicationObjectsInPDO = 0x00 }
#define OD_TPDO_COMM_DEFAULT(cob_id) \
    { .highestSub_indexSupported = 0x06, .COB_IDUsedByTPDO = (cob_id), \
      .transmissionType = 0xFE, .inhibitTime = 0x0000, .eventTimer = 0x0000, \
      .SYNCStartValue = 0x00 }
#define OD_TPDO_MAPPING_DEFAULT \
    { .numberOfMappedApplicationObjectsInPDO = 0x00 }

#define OD_RPDO_COMM_RECORDS(data) \
        { { .dataOrig = &(data).highestSub_indexSupported, .subIndex = 0, .attribute = ODA_SDO_R, .dataLength = 1 }, \
            { .dataOrig = &(data).COB_IDUsedByRPDO, .subIndex = 1, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).transmissionType, .subIndex = 2, .attribute = ODA_SDO_RW, .dataLength = 1 }, \
            { .dataOrig = &(data).eventTimer, .subIndex = 5, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 2 } }
#define OD_RPDO_MAPPING_RECORDS(data) \
        { { .dataOrig = &(data).numberOfMappedApplicationObjectsInPDO, .subIndex = 0, .attribute = ODA_SDO_RW, .dataLength = 1 }, \
            { .dataOrig = &(data).applicationObject1, .subIndex = 1, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject2, .subIndex = 2, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject3, .subIndex = 3, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject4, .subIndex = 4, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject5, .subIndex = 5, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject6, .subIndex = 6, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject7, .subIndex = 7, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).applicationObject8, .subIndex = 8, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 } }
#define OD_TPDO_COMM_RECORDS(data) \
        { { .dataOrig = &(data).highestSub_indexSupported, .subIndex = 0, .attribute = ODA_SDO_R, .dataLength = 1 }, \
            { .dataOrig = &(data).COB_IDUsedByTPDO, .subIndex = 1, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 4 }, \
            { .dataOrig = &(data).transmissionType, .subIndex = 2, .attribute = ODA_SDO_RW, .dataLength = 1 }, \
            { .dataOrig = &(data).inhibitTime, .subIndex = 3, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 2 }, \
            { .dataOrig = &(data).eventTimer, .subIndex = 5, .attribute = ODA_SDO_RW | ODA_MB, .dataLength = 2 }, \
            { .dataOrig = &(data).SYNCStartValue, .subIndex = 6, .attribute = ODA_SDO_RW, .dataLength = 1 } }
#define OD_TPDO_MAPPING_RECORDS(data) OD_RPDO_MAPPING_RECORDS(data)
#define OD_RPDO_EXTRA_RECORDS(slot) \
    OD_RPDO_COMM_RECORDS(OD_PERSIST_COMM.x1404_RPDOCommunicationParameter[slot])
#define OD_RPDO_EXTRA_MAPPING_RECORDS(slot) \
    OD_RPDO_MAPPING_RECORDS(OD_PERSIST_COMM.x1604_RPDOMappingParameter[slot])
#define OD_TPDO_EXTRA_RECORDS(slot) \
    OD_TPDO_COMM_RECORDS(OD_PERSIST_COMM.x1804_TPDOCommunicationParameter[slot])
#define OD_TPDO_EXTRA_MAPPING_RECORDS(slot) \
    OD_TPDO_MAPPING_RECORDS(OD_PERSIST_COMM.x1A04_TPDOMappingParameter[slot])

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    .x1016_consumerHeartbeatTime = {0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = OD_RPDO_COMM_DEFAULT(0x80000200),
    .x1401_RPDOCommunicationParameter = OD_RPDO_COMM_DEFAULT(0x80000300),
    .x1402_RPDOCommunicationParameter = OD_RPDO_COMM_DEFAULT(0x80000400),
    .x1403_RPDOCommunicationParameter = OD_RPDO_COMM_DEFAULT(0x80000500),
    .x1404_RPDOCommunicationParameter = {
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000),
        OD_RPDO_COMM_DEFAULT(0x80000000), OD_RPDO_COMM_DEFAULT(0x80000000)
    },
    .x1600_RPDOMappingParameter = OD_RPDO_MAPPING_DEFAULT,
    .x1601_RPDOMappingParameter = OD_RPDO_MAPPING_DEFAULT,
    .x1602_RPDOMappingParameter = OD_RPDO_MAPPING_DEFAULT,
    .x1603_RPDOMappingParameter = OD_RPDO_MAPPING_DEFAULT,
    .x1604_RPDOMappingParameter = {
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT,
        OD_RPDO_MAPPING_DEFAULT, OD_RPDO_MAPPING_DEFAULT
    },
    .x1800_TPDOCommunicationParameter = OD_TPDO_COMM_DEFAULT(0xC0000180),
    .x1801_TPDOCommunicationParameter = OD_TPDO_COMM_DEFAULT(0xC0000280),
    .x1802_TPDOCommunicationParameter = OD_TPDO_COMM_DEFAULT(0xC0000380),
    .x1803_TPDOCommunicationParameter = OD_TPDO_COMM_DEFAULT(0xC0000480),
    .x1804_TPDOCommunicationParameter = {
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000),
        OD_TPDO_COMM_DEFAULT(0xC0000000), OD_TPDO_COMM_DEFAULT(0xC0000000)
    },
    .x1A00_TPDOMappingParameter = OD_TPDO_MAPPING_DEFAULT,
    .x1A01_TPDOMappingParameter = OD_TPDO_MAPPING_DEFAULT,
    .x1A02_TPDOMappingParameter = OD_TPDO_MAPPING_DEFAULT,
    .x1A03_TPDOMappingParameter = OD_TPDO_MAPPING_DEFAULT,
    .x1A04_TPDOMappingParameter = {
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT, OD_TPDO_MAPPING_DEFAULT,
        OD_TPDO_MAPPING_DEFAULT
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    }
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1404_RPDOCommunicationParameter[OD_CNT_RPDO - 4][4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1604_RPDOMappingParameter[OD_CNT_RPDO - 4][9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1804_TPDOCommunicationParameter[OD_CNT_TPDO - 4][6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_record_t o_1A04_TPDOMappingParameter[OD_CNT_TPDO - 4][9];
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1404_RPDOCommunicationParameter = {
        OD_RPDO_EXTRA_RECORDS(0), OD_RPDO_EXTRA_RECORDS(1), OD_RPDO_EXTRA_RECORDS(2),
        OD_RPDO_EXTRA_RECORDS(3), OD_RPDO_EXTRA_RECORDS(4), OD_RPDO_EXTRA_RECORDS(5),
        OD_RPDO_EXTRA_RECORDS(6), OD_RPDO_EXTRA_RECORDS(7), OD_RPDO_EXTRA_RECORDS(8),
        OD_RPDO_EXTRA_RECORDS(9), OD_RPDO_EXTRA_RECORDS(10), OD_RPDO_EXTRA_RECORDS(11),
        OD_RPDO_EXTRA_RECORDS(12), OD_RPDO_EXTRA_RECORDS(13), OD_RPDO_EXTRA_RECORDS(14),
        OD_RPDO_EXTRA_RECORDS(15), OD_RPDO_EXTRA_RECORDS(16), OD_RPDO_EXTRA_RECORDS(17),
        OD_RPDO_EXTRA_RECORDS(18), OD_RPDO_EXTRA_RECORDS(19), OD_RPDO_EXTRA_RECORDS(20),
        OD_RPDO_EXTRA_RECORDS(21), OD_RPDO_EXTRA_RECORDS(22), OD_RPDO_EXTRA_RECORDS(23),
        OD_RPDO_EXTRA_RECORDS(24), OD_RPDO_EXTRA_RECORDS(25), OD_RPDO_EXTRA_RECORDS(26),
        OD_RPDO_EXTRA_RECORDS(27)
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1604_RPDOMappingParameter = {
        OD_RPDO_EXTRA_MAPPING_RECORDS(0), OD_RPDO_EXTRA_MAPPING_RECORDS(1),
        OD_RPDO_EXTRA_MAPPING_RECORDS(2), OD_RPDO_EXTRA_MAPPING_RECORDS(3),
        OD_RPDO_EXTRA_MAPPING_RECORDS(4), OD_RPDO_EXTRA_MAPPING_RECORDS(5),
        OD_RPDO_EXTRA_MAPPING_RECORDS(6), OD_RPDO_EXTRA_MAPPING_RECORDS(7),
        OD_RPDO_EXTRA_MAPPING_RECORDS(8), OD_RPDO_EXTRA_MAPPING_RECORDS(9),
        OD_RPDO_EXTRA_MAPPING_RECORDS(10), OD_RPDO_EXTRA_MAPPING_RECORDS(11),
        OD_RPDO_EXTRA_MAPPING_RECORDS(12), OD_RPDO_EXTRA_MAPPING_RECORDS(13),
        OD_RPDO_EXTRA_MAPPING_RECORDS(14), OD_RPDO_EXTRA_MAPPING_RECORDS(15),
        OD_RPDO_EXTRA_MAPPING_RECORDS(16), OD_RPDO_EXTRA_MAPPING_RECORDS(17),
        OD_RPDO_EXTRA_MAPPING_RECORDS(18), OD_RPDO_EXTRA_MAPPING_RECORDS(19),
        OD_RPDO_EXTRA_MAPPING_RECORDS(20), OD_RPDO_EXTRA_MAPPING_RECORDS(21),
        OD_RPDO_EXTRA_MAPPING_RECORDS(22), OD_RPDO_EXTRA_MAPPING_RECORDS(23),
        OD_RPDO_EXTRA_MAPPING_RECORDS(24), OD_RPDO_EXTRA_MAPPING_RECORDS(25),
        OD_RPDO_EXTRA_MAPPING_RECORDS(26), OD_RPDO_EXTRA_MAPPING_RECORDS(27)
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1804_TPDOCommunicationParameter = {
        OD_TPDO_EXTRA_RECORDS(0), OD_TPDO_EXTRA_RECORDS(1), OD_TPDO_EXTRA_RECORDS(2),
        OD_TPDO_EXTRA_RECORDS(3), OD_TPDO_EXTRA_RECORDS(4), OD_TPDO_EXTRA_RECORDS(5),
        OD_TPDO_EXTRA_RECORDS(6), OD_TPDO_EXTRA_RECORDS(7), OD_TPDO_EXTRA_RECORDS(8),
        OD_TPDO_EXTRA_RECORDS(9), OD_TPDO_EXTRA_RECORDS(10), OD_TPDO_EXTRA_RECORDS(11),
        OD_TPDO_EXTRA_RECORDS(12), OD_TPDO_EXTRA_RECORDS(13), OD_TPDO_EXTRA_RECORDS(14),
        OD_TPDO_EXTRA_RECORDS(15), OD_TPDO_EXTRA_RECORDS(16), OD_TPDO_EXTRA_RECORDS(17),
        OD_TPDO_EXTRA_RECORDS(18), OD_TPDO_EXTRA_RECORDS(19), OD_TPDO_EXTRA_RECORDS(20),
        OD_TPDO_EXTRA_RECORDS(21), OD_TPDO_EXTRA_RECORDS(22), OD_TPDO_EXTRA_RECORDS(23),
        OD_TPDO_EXTRA_RECORDS(24), OD_TPDO_EXTRA_RECORDS(25), OD_TPDO_EXTRA_RECORDS(26),
        OD_TPDO_EXTRA_RECORDS(27)
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A04_TPDOMappingParameter = {
        OD_TPDO_EXTRA_MAPPING_RECORDS(0), OD_TPDO_EXTRA_MAPPING_RECORDS(1),
        OD_TPDO_EXTRA_MAPPING_RECORDS(2), OD_TPDO_EXTRA_MAPPING_RECORDS(3),
        OD_TPDO_EXTRA_MAPPING_RECORDS(4), OD_TPDO_EXTRA_MAPPING_RECORDS(5),
        OD_TPDO_EXTRA_MAPPING_RECORDS(6), OD_TPDO_EXTRA_MAPPING_RECORDS(7),
        OD_TPDO_EXTRA_MAPPING_RECORDS(8), OD_TPDO_EXTRA_MAPPING_RECORDS(9),
        OD_TPDO_EXTRA_MAPPING_RECORDS(10), OD_TPDO_EXTRA_MAPPING_RECORDS(11),
        OD_TPDO_EXTRA_MAPPING_RECORDS(12), OD_TPDO_EXTRA_MAPPING_RECORDS(13),
        OD_TPDO_EXTRA_MAPPING_RECORDS(14), OD_TPDO_EXTRA_MAPPING_RECORDS(15),
        OD_TPDO_EXTRA_MAPPING_RECORDS(16), OD_TPDO_EXTRA_MAPPING_RECORDS(17),
        OD_TPDO_EXTRA_MAPPING_RECORDS(18), OD_TPDO_EXTRA_MAPPING_RECORDS(19),
        OD_TPDO_EXTRA_MAPPING_RECORDS(20), OD_TPDO_EXTRA_MAPPING_RECORDS(21),
        OD_TPDO_EXTRA_MAPPING_RECORDS(22), OD_TPDO_EXTRA_MAPPING_RECORDS(23),
        OD_TPDO_EXTRA_MAPPING_RECORDS(24), OD_TPDO_EXTRA_MAPPING_RECORDS(25),
        OD_TPDO_EXTRA_MAPPING_RECORDS(26), OD_TPDO_EXTRA_MAPPING_RECORDS(27)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1404, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[0], NULL},
    {0x1405, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[1], NULL},
    {0x1406, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[2], NULL},
    {0x1407, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[3], NULL},
    {0x1408, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[4], NULL},
    {0x1409, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[5], NULL},
    {0x140A, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[6], NULL},
    {0x140B, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[7], NULL},
    {0x140C, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[8], NULL},
    {0x140D, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[9], NULL},
    {0x140E, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[10], NULL},
    {0x140F, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[11], NULL},
    {0x1410, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[12], NULL},
    {0x1411, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[13], NULL},
    {0x1412, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[14], NULL},
    {0x1413, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[15], NULL},
    {0x1414, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[16], NULL},
    {0x1415, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[17], NULL},
    {0x1416, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[18], NULL},
    {0x1417, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[19], NULL},
    {0x1418, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[20], NULL},
    {0x1419, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[21], NULL},
    {0x141A, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[22], NULL},
    {0x141B, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[23], NULL},
    {0x141C, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[24], NULL},
    {0x141D, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[25], NULL},
    {0x141E, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[26], NULL},
    {0x141F, 0x04, ODT_REC, &ODObjs.o_1404_RPDOCommunicationParameter[27], NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1604, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[0], NULL},
    {0x1605, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[1], NULL},
    {0x1606, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[2], NULL},
    {0x1607, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[3], NULL},
    {0x1608, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[4], NULL},
    {0x1609, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[5], NULL},
    {0x160A, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[6], NULL},
    {0x160B, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[7], NULL},
    {0x160C, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[8], NULL},
    {0x160D, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[9], NULL},
    {0x160E, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[10], NULL},
    {0x160F, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[11], NULL},
    {0x1610, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[12], NULL},
    {0x1611, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[13], NULL},
    {0x1612, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[14], NULL},
    {0x1613, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[15], NULL},
    {0x1614, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[16], NULL},
    {0x1615, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[17], NULL},
    {0x1616, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[18], NULL},
    {0x1617, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[19], NULL},
    {0x1618, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[20], NULL},
    {0x1619, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[21], NULL},
    {0x161A, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[22], NULL},
    {0x161B, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[23], NULL},
    {0x161C, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[24], NULL},
    {0x161D, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[25], NULL},
    {0x161E, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[26], NULL},
    {0x161F, 0x09, ODT_REC, &ODObjs.o_1604_RPDOMappingParameter[27], NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1804, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[0], NULL},
    {0x1805, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[1], NULL},
    {0x1806, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[2], NULL},
    {0x1807, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[3], NULL},
    {0x1808, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[4], NULL},
    {0x1809, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[5], NULL},
    {0x180A, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[6], NULL},
    {0x180B, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[7], NULL},
    {0x180C, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[8], NULL},
    {0x180D, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[9], NULL},
    {0x180E, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[10], NULL},
    {0x180F, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[11], NULL},
    {0x1810, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[12], NULL},
    {0x1811, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[13], NULL},
    {0x1812, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[14], NULL},
    {0x1813, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[15], NULL},
    {0x1814, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[16], NULL},
    {0x1815, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[17], NULL},
    {0x1816, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[18], NULL},
    {0x1817, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[19], NULL},
    {0x1818, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[20], NULL},
    {0x1819, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[21], NULL},
    {0x181A, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[22], NULL},
    {0x181B, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[23], NULL},
    {0x181C, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[24], NULL},
    {0x181D, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[25], NULL},
    {0x181E, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[26], NULL},
    {0x181F, 0x06, ODT_REC, &ODObjs.o_1804_TPDOCommunicationParameter[27], NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x1A04, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[0], NULL},
    {0x1A05, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[1], NULL},
    {0x1A06, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[2], NULL},
    {0x1A07, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[3], NULL},
    {0x1A08, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[4], NULL},
    {0x1A09, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[5], NULL},
    {0x1A0A, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[6], NULL},
    {0x1A0B, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[7], NULL},
    {0x1A0C, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[8], NULL},
    {0x1A0D, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[9], NULL},
    {0x1A0E, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[10], NULL},
    {0x1A0F, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[11], NULL},
    {0x1A10, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[12], NULL},
    {0x1A11, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[13], NULL},
    {0x1A12, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[14], NULL},
    {0x1A13, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[15], NULL},
    {0x1A14, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[16], NULL},
    {0x1A15, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[17], NULL},
    {0x1A16, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[18], NULL},
    {0x1A17, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[19], NULL},
    {0x1A18, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[20], NULL},
    {0x1A19, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[21], NULL},
    {0x1A1A, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[22], NULL},
    {0x1A1B, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[23], NULL},
    {0x1A1C, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[24], NULL},
    {0x1A1D, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[25], NULL},
    {0x1A1E, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[26], NULL},
    {0x1A1F, 0x09, ODT_REC, &ODObjs.o_1A04_TPDOMappingParameter[27], NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
